'use client';

import { useState, useEffect } from 'react';
import { ROLES_DATA, RoleData } from '@/lib/roles-data';
import { RoleCard } from '@/components/explore/RoleCard';
import { RoleCompare } from '@/components/explore/RoleCompare';
import { CurriculumPreviewModal } from '@/components/explore/CurriculumPreviewModal';
import { Input } from '@/components/ui/input';
import { Search, Compass, Users } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';

export default function ExplorePage() {
  const [searchQuery, setSearchQuery] = useState('');
  const [activeFilter, setActiveFilter] = useState('All');
  const [previewRole, setPreviewRole] = useState<RoleData | null>(null);
  
  // Hardcoded for demo/UI matching instead of a real API call since we don't have public curricula properly modeled yet
  const communityCurricula = [
    { role: 'Data Scientist', level: 'Beginner', weeks: 20, timeAgo: '2 hours ago', author: 'B.Tech CSE Student' },
    { role: 'Full Stack Developer', level: 'Intermediate', weeks: 14, timeAgo: '5 hours ago', author: 'A student in Delhi' },
    { role: 'UI/UX Designer', level: 'Beginner', weeks: 10, timeAgo: '1 day ago', author: 'BCA Student' },
  ];

  const filters = ['All', 'Tech', 'Data', 'Design', 'Management', 'Marketing'];

  const filteredRoles = ROLES_DATA.filter((role) => {
    const matchesFilter = activeFilter === 'All' || role.category === activeFilter;
    const searchLower = searchQuery.toLowerCase();
    const matchesSearch = 
      role.name.toLowerCase().includes(searchLower) ||
      role.skills.some(s => s.toLowerCase().includes(searchLower));
    return matchesFilter && matchesSearch;
  });

  return (
    <div className="space-y-12 animate-in fade-in duration-500 pb-10">
      
      {/* Header */}
      <div>
        <h1 className="text-3xl sm:text-4xl font-bold text-white tracking-tight mb-3 flex items-center gap-3">
          <Compass className="h-8 w-8 text-indigo-400" /> Explore Learning Paths
        </h1>
        <p className="text-slate-400 text-lg max-w-2xl">
          Discover high-demand career paths, compare salaries and requirements, and generate a customized curriculum instantly.
        </p>
      </div>

      {/* SECTION 1: Search & Filter Bar */}
      <div className="bg-slate-900/50 border border-slate-800 rounded-2xl p-4 sm:p-6 flex flex-col md:flex-row gap-6 justify-between items-center sticky top-[72px] z-20 backdrop-blur-md">
        <div className="relative w-full md:w-96">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-slate-500" />
          <Input 
            type="text"
            placeholder="Search by role, skill (e.g. React)..." 
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="pl-10 bg-slate-950 border-slate-800 focus-visible:ring-indigo-500 text-slate-200"
          />
        </div>

        <div className="flex items-center gap-2 overflow-x-auto w-full md:w-auto pb-2 md:pb-0 hide-scrollbar">
          {filters.map((filter) => (
            <button
              key={filter}
              onClick={() => setActiveFilter(filter)}
              className={`px-4 py-1.5 rounded-full text-sm font-medium whitespace-nowrap transition-colors ${
                activeFilter === filter 
                  ? 'bg-indigo-600 text-white' 
                  : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
              }`}
            >
              {filter}
            </button>
          ))}
        </div>

        <div className="w-full md:w-auto shrink-0">
          <RoleCompare />
        </div>
      </div>

      {/* SECTION 2: Role Cards Grid */}
      <div>
        <div className="mb-6 flex justify-between items-end">
          <h2 className="text-2xl font-bold text-slate-200">Career Paths <span className="text-slate-500 font-medium text-lg ml-2">({filteredRoles.length})</span></h2>
        </div>
        
        {filteredRoles.length === 0 ? (
          <div className="bg-slate-900/50 border border-slate-800 border-dashed rounded-2xl p-12 text-center">
            <p className="text-slate-400 text-lg">No roles found matching "{searchQuery}". Try a different skill or filter.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredRoles.map((role) => (
              <RoleCard key={role.id} role={role} onPreview={setPreviewRole} />
            ))}
          </div>
        )}
      </div>

      {/* SECTION 3: Community Curricula */}
      <div className="pt-8 border-t border-slate-800">
        <h2 className="text-2xl font-bold text-slate-200 mb-6 flex items-center gap-2">
          <Users className="h-6 w-6 text-indigo-400" /> Recently Generated by Community
        </h2>
        
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {communityCurricula.map((item, i) => (
            <div key={i} className="bg-slate-900/30 border border-slate-800 rounded-xl p-5">
              <div className="flex justify-between items-start mb-2">
                <span className="text-xs text-slate-500">{item.timeAgo}</span>
                <span className="text-xs bg-slate-800 text-slate-400 px-2 py-0.5 rounded border border-slate-700">{item.level}</span>
              </div>
              <p className="text-white font-bold mb-1">{item.role}</p>
              <p className="text-sm text-indigo-400 mb-4">{item.weeks} Week Path</p>
              <div className="pt-3 border-t border-slate-800 text-xs text-slate-500">
                Created by: <span className="text-slate-400">{item.author}</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Modal */}
      <CurriculumPreviewModal 
        role={previewRole} 
        isOpen={!!previewRole} 
        onClose={() => setPreviewRole(null)} 
      />
    </div>
  );
}
